stages:
    - build

editgithub:
  before_script:
    - git config --global user.name "${GITLAB_USER_NAME}"
    - git config --global user.email "${GITLAB_USER_EMAIL}"
  stage: build
  script:
    - export JOB_PATH=$(pwd)
    - '/Users/ec2-user/CambiaSwift $G_COMMIT $G_CHECK "$JOB_PATH/Package.swift"'
    - git add Package.swift
    - git commit -m "$G_COMMIT"
    - git push -o ci.skip https://root:$UPLOAD_TOKEN@$CI_SERVER_HOST/$CI_PROJECT_PATH.git HEAD:main
    - git tag "v$G_COMMIT-pre"
    - git tag      
    - git push --tags https://root:$UPLOAD_TOKEN@$CI_SERVER_HOST/$CI_PROJECT_PATH.git HEAD:main
  tags:
        - macos
  when: manual
